### ISSUE TITLE
update Readme

### ISSUE THREAD

**Issue by ye-russell** [h5p/h5p-image#71]
It is not clear how to use it? Can we extend the readme with use cases?

**Comment by otacke** [comment]
@ye-russell It is not useful on its owm, but just in combination with H5P (see https://h5p.org).

**Comment by ye-russell** [comment]
@otacke Is this just an extension of the built-in image type? How can we utilize it? Should we add a dependency in the library.json and use it as a widget for this field in semantics?

**Comment by otacke** [comment]
This library is a standalone content type for images, you could call it an extension of the internal widget, yes. 

You'd use the internal widget if all you or your user needs is the image path, e.g. if you want to use the image as the background of some element. You will need to provide the code to handle it yourself.

This library, however, is a content type that ships with all the code for displaying the image (or a placeholder) and contains all the code to handle user settings like the alt tag text (and a couple of other options soon). You'd use it if your content type should display the image like any other subcontent type using H5P's `newRunnable` function. If you want to do that, then you would normally use it in a `library` field in `semantics.json` (https://h5p.org/semantics#type-library). No need to add a hard dependency in `library.json`. There may be use cases to do the latter, but probably not as frequent.
